spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: localhost
    port: 25

application:
  security:
    jwt:
      secret-key: dGVzdFNlY3JldEtleU11c3RCZUJhc2U2NEJpdFNlY3JldA==
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account