name: CI/CD – Telecom Frontend

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  # ══════════════════════════════════════════════
  # JOB 1 — Lint
  # ══════════════════════════════════════════════
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: telecom-frontend/package-lock.json
      - run: npm ci --legacy-peer-deps
        working-directory: telecom-frontend
      - run: npm run lint
        working-directory: telecom-frontend

  # ══════════════════════════════════════════════
  # JOB 2 — Tests Unitaires
  # ══════════════════════════════════════════════
  test:
    name: Tests Unitaires
    runs-on: ubuntu-latest
    needs: lint
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: telecom-frontend/package-lock.json
      - run: npm ci --legacy-peer-deps
        working-directory: telecom-frontend
      - run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: telecom-frontend
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: telecom-frontend/coverage/
          retention-days: 7

  # ══════════════════════════════════════════════
  # JOB 3 — SonarCloud
  # ══════════════════════════════════════════════
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: telecom-frontend
          args: >
            -Dsonar.projectKey=bannournefzi_ticket-management
            -Dsonar.organization=bannournefzi
            -Dsonar.sources=src
            -Dsonar.exclusions=**/*.spec.ts,**/node_modules/**
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info

    # ══════════════════════════════════════════════
  # JOB 4 — Build Angular
  # ══════════════════════════════════════════════
  build:
    name: Build Angular
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: telecom-frontend/package-lock.json
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: telecom-frontend
      - name: Fix TypeScript version
        run: npm install typescript@5.1.6 --save-dev --legacy-peer-deps
        working-directory: telecom-frontend
      - name: Build Angular
        run: npm run build -- --configuration production
        working-directory: telecom-frontend
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: telecom-frontend/dist/
          retention-days: 7

  # ══════════════════════════════════════════════
  # JOB 5 — Docker Build & Push → Docker Hub
  # ══════════════════════════════════════════════
  docker:
    name: Docker Build & Push → Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extraire les métadonnées Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/telecom-frontend
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=sha-

      - name: Build and Push → Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./telecom-frontend
          file: ./telecom-frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Résumé Docker
        run: |
          echo "## Docker Build & Push" >> $GITHUB_STEP_SUMMARY
          echo "| Champ | Valeur |" >> $GITHUB_STEP_SUMMARY
          echo "|---|---|" >> $GITHUB_STEP_SUMMARY
          echo "| Image | \`${{ secrets.DOCKERHUB_USERNAME }}/telecom-frontend:latest\` |" >> $GITHUB_STEP_SUMMARY
          echo "| SHA | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY

  # # ══════════════════════════════════════════════
  # # JOB 6 — Deploy Azure
  # # ══════════════════════════════════════════════
  # deploy:
  #   name: Deploy to Azure
  #   runs-on: ubuntu-latest
  #   needs: docker
  #   if: github.ref == 'refs/heads/develop'
  #   steps:
  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: telecom-frontend
  #         publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  #         images: ${{ secrets.DOCKERHUB_USERNAME }}/telecom-frontend:latest